rails/solid_queue

README.md

Without it, I'm getting error:
```
YAML syntax error occurred while parsing /path-to-app/config/solid_queue.yml. Please note that YAML must be consistently indented using spaces. Tabs are not allowed. Error: (<unknown>): did not find expected alphabetic or numeric character while scanning an alias at line 6 column 15
```
when starting `bundle exec rake solid_queue:start`
Please note that the latter example `staging*` works fine as is.

Update example for all queues sign

---

db/migrate/20231211200639_create_solid_queue_tables.rb

Hey,
First of all, thank you so much for amazing Solid Queue! ❤️
Migrations are using version 7.1, but support is provided from Rails 7.0 onwards, so users installing migrations using Rails 7.0 will get an error and will have to manually change the version of the migrations class. This PR fixes that.

Use ActiveRecord::Migration[7.0] in migrations

---

lib/generators/solid_queue/install/install_generator.rb
lib/generators/solid_queue/install/templates/config.yml

The install steps eluded to a configuration not needed (an empty file will suffice) so I ran the install generator and ran into this error.
```bash
± bundle exec rails solid_queue:start
bin/rails aborted!
Configuration for Solid Queue not found in /Users/chris/code/solidqueue-example/config/solid_queue.yml
Tasks: TOP => solid_queue:start
(See full trace by running task with --trace)
```
This PR adds an example `config/solid_queue.yml` file to the generator to fix this error on install and provide an easy to customize example config.
Should make it a bit easier to use and customize. 👍 
Thanks for all your hard work @rosa!!
Edit: I just saw on your other PR that you were going to delete the generator, so feel free to close this if you want. This might be a useful reason to keep the …

Copy over example config on install

---

README.md

This fixes the indentation of a few multi-paragraph list items.
| Before | After |
| --- | --- |
| ![before](https://github.com/basecamp/solid_queue/assets/771968/9a11ea3a-ae7e-4329-85c0-01e9a6d41a64) | ![after](https://github.com/basecamp/solid_queue/assets/771968/0784c11c-8f41-4b05-9501-1a00668902d1) |
I also snuck in a 2nd commit that fixes a typo in a configuration example: `solid_queue.config.connects_to` => `config.solid_queue.connects_to`.

Fix indentation in README

---

lib/solid_queue/processes/runnable.rb

closes https://github.com/basecamp/solid_queue/issues/75

Make sure we wrap runnable code in app's executor.

---

app/models/solid_queue/job/executable.rb

I think it's useful and a common thing to query all the failed jobs.
I added a scope for it.

feature: add failed scope to job

---

Gemfile.lock
lib/puma/plugin/solid_queue.rb
solid_queue.gemspec
test/dummy/config/puma.rb
test/integration/puma/plugin_test.rb

To be able to use app's code we need to wait for puma to boot before we start SolidQueue's supervisor. 
closes https://github.com/basecamp/solid_queue/issues/77

Run Supervisor only when puma is fully booted.

---

Gemfile.lock
README.md
app/models/solid_queue/failed_execution.rb
app/models/solid_queue/job.rb
solid_queue.gemspec
test/integration/puma/plugin_test.rb

So we can simplify the calls to `serialize` for `Job` and `FailedExecution`.

Require Rails >= 7.1

---

app/models/solid_queue/execution/job_attributes.rb

Hi there and thanks for all the efforts on this great library!
I just started following this repository (recently started SolidQueue in my project and am very excited to deepen integration as cron-like tasks get supported in the near future), and as I was scanning some of the new code I noticed this small typo, so I figured I'd submit a quick PR to help a tiny bit. Simply changes `assumible` -> `assumable`.
Thanks again for the great work on this project!

Fix small typo in job_attributes.rb

---

app/models/solid_queue/job.rb
test/models/solid_queue/job_test.rb

Follow-up to https://github.com/basecamp/solid_queue/pull/93/
This is necessary so that the log subscriber doesn't crash. I had missed the pull request https://github.com/rails/rails/pull/47844, merged after the original `perform_all_later` feature was added to Active Job.

Set `successfully_enqueued` for jobs enqueued in batch and return enqueued count

---

lib/generators/solid_queue/install/templates/config.yml

Prior to this change, if all #'s are removed from the config template you're left with is a yaml file that solid_queue can't parse.
```
bundle exec rake solid_queue:start
rake aborted!
YAML syntax error occurred while parsing
/project/config/solid_queue.yml. Please note
that YAML must be consistently indented using spaces. Tabs are not
allowed. Error: (<unknown>): did not find expected key while parsing a
block mapping at line 1 column 1
```
reproducable in this repo via (remove comments first).  After fix:
```
ActiveSupport::ConfigurationFile.parse("./lib/generators/solid_queue/install/templates/config.yml")["development"]
=> {"batch_size"=>10, "dispatchers"=>[{"polling_interval"=>1,
"batch_size"=>500}], "workers"=>[{"queues"=>"*", "threads"=>5,
"processes"=>1, "polling_interval"=>0.1}]} …
```

Fix config.yml template indentation

---

app/models/solid_queue/semaphore.rb
test/integration/concurrency_controls_test.rb

This tries to address a tricky deadlock we've seen about once every couple of days, where _three_ jobs that compete for the semaphore are enqueued at the same time. One of them wins at creating the semaphore, and the other two transactions acquire a shared lock over the just created semaphore row, by key. Then, they try to upgrade that lock to an exclusive lock to perform an UPDATE (attempting to decrement the semaphore), leading to a deadlock because each one of them is waiting for the other one to release the shared lock.
From `SHOW ENGINE INNODB STATUS`:
```
------------------------
LATEST DETECTED DEADLOCK
------------------------
2023-12-27 07:57:28 140410341029440
*** (1) TRANSACTION:
TRANSACTION 1972990032, ACTIVE 1 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT …
```

Retry once after getting a deadlock when attempting to decrement a semaphore

---

app/models/solid_queue/claimed_execution.rb
app/models/solid_queue/job/executable.rb
test/dummy/config/environments/test.rb
test/integration/concurrency_controls_test.rb

That's it, don't try to gain the concurrency lock, because claimed executions with concurrency limits that are released would most likely be holding the semaphore themselves, as it's released after completing. This means these claimed executions would go to _blocked_ upon release, leaving the semaphore busy. Just assume that if a job has a claimed execution, it's because it already gained the lock when going to _ready_.

Don't go through the general dispatch flow when releasing claimed executions

---

app/models/solid_queue/job/clearable.rb

ActiveRecord batching can be slow when looping over records filtered by non-PKs. We don't care about the order of deletion here, so we can just use a loop to delete the clearable jobs; this allows us to achieve better performance in general.
/cc @rosa @djmb

Clear clearable jobs in a loop instead of batching

---

app/models/solid_queue/claimed_execution.rb
app/models/solid_queue/execution.rb
app/models/solid_queue/execution/dispatching.rb
app/models/solid_queue/failed_execution.rb
app/models/solid_queue/job/concurrency_controls.rb
app/models/solid_queue/job/executable.rb
app/models/solid_queue/queue.rb
app/models/solid_queue/ready_execution.rb
app/models/solid_queue/scheduled_execution.rb
app/models/solid_queue/semaphore.rb
test/dummy/app/jobs/raising_job.rb
test/integration/jobs_lifecycle_test.rb
test/models/solid_queue/claimed_execution_test.rb
test/models/solid_queue/failed_execution_test.rb
test/models/solid_queue/job_test.rb
test/models/solid_queue/ready_execution_test.rb

- `retry_all` is implemented by selecting failed executions, locking them, dispatching their jobs and deleting them. 
This is very similar to the work we have to do when dispatching scheduled executions, so this extracts that common functionality into its own concern.
- `discard_all` makes some concessions. It's intended to be used in very specific, emergency situations, so that's ok. First, it starts from the execution records, as we need to lock them before the jobs to avoid jobs changing state while they're being discarded. Because of this, we can only discard jobs in the same state together in the same batch. Then, when discarding ready executions that are concurrency-limited, we need to unblock the next jobs. Since we're aiming for performance here and this is not to be used in …

Implement retry_all and discard_all

---

app/models/solid_queue/job/executable.rb
app/models/solid_queue/job/schedulable.rb
test/models/solid_queue/job_test.rb

This is prone to race conditions and stale reads, and it's just intended for use in Mission Control or other reporting tools, not for regular operation.

Expose `SolidQueue::Job#status`

---

README.md

This was proposed as resolution to issue #102.
Specifically in [the last comment](https://github.com/basecamp/solid_queue/issues/102#issuecomment-1872307699)
Please feel free to change wording/formatting if you think this doesn't quite fit.

Add a note in the readme advising on configuration file use

---

README.md

fix mission_control mention in README
mission_control-jobs has been released, so the README needs some minor updates.

fix mission_control mention in README

---

app/models/solid_queue/semaphore.rb

This was added in d72fe4607f8fc5aacc07c6314fb5aa0af200d6f0 and initially, it seemed like a good idea, but it ended up causing a different error as it messed with Active Record's transactions. The error would be
```
ActiveRecord::StatementInvalid (Mysql2::Error: SAVEPOINT active_record_1 does not exist)
```
And this made us realise it might be more complicated, because we might be in a transaction that wraps the Solid Queue transaction.
Since this is such an edge case that happens only with certain job loads and perhaps only with MySQL, InnoDB and READ COMMITTED, let's stop trying to be too clever about it, and instead, simplify this a bit by avoiding the decrement at all when the semaphore's limit is 1 and it was just created.

Stop retrying semaphore decrement when getting a deadlock

---

app/models/solid_queue/blocked_execution.rb

**Detail**
Improve memory usage
**Additional information**
Benchmark script:
```ruby
require "benchmark/ips"
require "benchmark/memory"
def releasable(concurrency_keys)
semaphores = SolidQueue::Semaphore.where(key: concurrency_keys).select(:key, :value).index_by(&:key)
(concurrency_keys - semaphores.keys) | semaphores.select { |key, semaphore| semaphore.value > 0 }.map(&:first)
end
def refactored_releasable(concurrency_keys)
semaphores = SolidQueue::Semaphore.where(key: concurrency_keys).pluck(:key, :value).to_h
(concurrency_keys - semaphores.keys) | semaphores.select { |_key, value| value > 0 }.keys
end
def concurrency_keys
('a'..'z').to_a
end
def seed
SolidQueue::Semaphore.where(key: concurrency_keys).delete_all
concurrency_keys.each_with_index do |key, i| …
```

improve memory usage for releasable concurrency keys

---

app/models/solid_queue/execution/dispatching.rb
app/models/solid_queue/scheduled_execution.rb
test/unit/dispatcher_test.rb

This was missing and makes the locking prone to deadlocks when we have a bunch of jobs scheduled at the same time with the same priority, since we'd have a non-deterministic ordering.
Besides, on the `DELETE` query, force `ORDER BY job_id` even if we don't care about that. It turns out, under certain circumstances, when the scheduled_executions table is too small, MySQL might choose not to use any indexes for the `DELETE` by `job_id`. This means it might lock other rows besides those it's going to delete. Then, when running more than one dispatcher doing this, we might end up with a deadlock because one dispatcher is deleting and locking some rows that is not going to delete, and the other is doing the same, and both are waiting for the other's lock.
This deadlock was happening …

Include job_id in order clause when fetching scheduled jobs to dispatch and when dispatching

---

README.md
lib/solid_queue/configuration.rb

Change number of threads per worker by default to 3 instead of 5

---

app/models/solid_queue/job/clearable.rb
test/integration/jobs_lifecycle_test.rb

I'll give this a try. Please let me know if it could be improved.
This is a suggestion originating from https://github.com/basecamp/solid_queue/pull/155#issuecomment-1979577345 to add a `class_name:` option to `clear_finished_in_batches`.
Instead of exposing new configuration settings to Solid Queue for controlling the expiry of specific jobs this PR would enable anyone to write their own custom cleanup logic and still rely on the core cleanup functionality.

Add option to limit clearing of jobs to specific class name(s)

---

README.md

There are a couple of closed issues asking about horizontal scaling:
- https://github.com/basecamp/solid_queue/issues/85
- https://github.com/basecamp/solid_queue/issues/138
... and I had the same questions. @rosa [kindly mentioned](https://github.com/basecamp/solid_queue/issues/138#issuecomment-1915016050) that they are planning to write a blog post detailing some setup, monitoring, and alerts suggestions. In the meantime, I thought it would be nice to mention some basics in the README, which is what this PR does.

Describe horizontal scaling support in README.md

---

Gemfile.lock
solid_queue.gemspec

Addresses issue #156 
`solid_queue` does not appear to depend on the whole Rails stack.
```ruby
require "rails"
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "action_controller/railtie"
require "action_view/railtie"
require "rails/test_unit/railtie"
require "rails/engine/commands"
```
This PR reduces dependencies to the following, but maybe it only needs `railties`?
```ruby
rails_version = ">= 7.1"
spec.add_dependency "activerecord", rails_version
spec.add_dependency "activejob", rails_version
spec.add_dependency "railties", rails_version
```

Refactor to remove Rails dependency

---

app/models/solid_queue/job/schedulable.rb

When looking on a way to compute a queue latency, I was looking for scopes to find jobs that have not run yet.
Looks like `scheduled` is the one, but the implementation seems incorrect. It's actually the same as `finished`.

Fix scheduled scope

---

app/models/solid_queue/process/prunable.rb

This seems a little trivial to suggest (sorry!) but using a range in Rails 7.1 turns the query value into a proper bind parameter and preparable statement. This [will become unnecessary](https://github.com/rails/rails/pull/51139) in the next release of Rails. And I like the beginless/endless queries and all the other queries in SolidQueue that I could find use this style too 👍🏻 
Here's a writeup with a little more info: https://island94.org/2024/03/rails-active-record-will-it-bind

Use beginless range for query instead of `< ?`

---

lib/puma/plugin/solid_queue.rb
test/integration/puma/plugin_test.rb

Without doing so SolidQueue would be running making Puma not properly stop so when Puma tries to start its process again we would get `Errno::EADDRINUSE` error.
Closes #180

Stop SolidQueue on puma restart when puma plugin is used.

---

lib/generators/solid_queue/install/templates/config.yml

The generated config file still has the worker count of 5, not 3. This led to issues in development as connections were quickly used up causing jobs to be stuck.
I think this was missed as part of #137

Fix the worker count in the generated config file.

---

lib/solid_queue.rb

```
$> bin/rails generate solid_queue:install
/home/solid_queue/lib/solid_queue.rb:26:in `<module:SolidQueue>': undefined method `seconds' for 60:Integer (NoMethodError)
Did you mean?  send
from /home/solid_queue/lib/solid_queue.rb:20:in `<main>'
from <internal:/home/.asdf/installs/ruby/3.0.6/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
from <internal:/home/.asdf/installs/ruby/3.0.6/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
from /home/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
from /home/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/bundler-2.4.18/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
from …
```

fix active support load

---

README.md
lib/active_job/queue_adapters/solid_queue_adapter.rb
lib/solid_queue.rb

The `enqueue_after_transaction_commit` method was recently added to ActiveJob to be supported by the adapters.
PR: https://github.com/rails/rails/pull/51426

Added enqueue_after_transaction_commit setting

---

README.md
lib/solid_queue.rb

After some great points raised on #212, and the suggestion given by the same Rails guides. This was the original value set in #209, that was changed as I suggested it 😅 .

Set `enqueue_after_transaction_commit` to `false` by default

---

app/models/solid_queue/blocked_execution.rb
app/models/solid_queue/claimed_execution.rb
app/models/solid_queue/execution.rb
app/models/solid_queue/execution/dispatching.rb
app/models/solid_queue/failed_execution.rb
app/models/solid_queue/job/executable.rb
app/models/solid_queue/process.rb
app/models/solid_queue/process/prunable.rb
app/models/solid_queue/recurring_execution.rb
app/models/solid_queue/scheduled_execution.rb
lib/solid_queue.rb
lib/solid_queue/app_executor.rb
lib/solid_queue/dispatcher.rb
lib/solid_queue/dispatcher/recurring_task.rb
lib/solid_queue/engine.rb
lib/solid_queue/log_subscriber.rb
lib/solid_queue/processes/base.rb
lib/solid_queue/processes/poller.rb
lib/solid_queue/processes/registrable.rb
lib/solid_queue/processes/runnable.rb
lib/solid_queue/processes/signals.rb
lib/solid_queue/supervisor.rb
lib/solid_queue/worker.rb
test/integration/instrumentation_test.rb
test/integration/processes_lifecycle_test.rb
test/unit/log_subscriber_test.rb

This includes the basics to make it work, plus instrumentation for the most relevant actions. 
Closes #103.

Rely on `ActiveSupport::Notifications` and `ActiveSupport::LogSubscriber` for logging and instrumentation

---

app/models/solid_queue/semaphore.rb
test/integration/instrumentation_test.rb
test/test_helper.rb

Avoid crashing in this case, just assume concurrency limit is 1. This shouldn't happen with normal operation but we've had this problem when jobs that are concurrency-limited are enqueued from new code and dispatched from old code, where the job still doesn't have concurrency controls, thus returning `nil` for the limit and crashing the dispatcher.

Handle case of concurrency limit not being set in Semaphore

---

lib/solid_queue/processes/registrable.rb
lib/solid_queue/supervisor.rb

Otherwise, the process prune thread seems to interfere with each forks' threads reloading, [making them come to a halt](https://github.com/rails/solid_queue/issues/204) when code is changed and they need to reload one at a time.

Launch process prune from supervisor after forking supervised processes 

---

Gemfile.lock
solid_queue.gemspec

Update fugit version to 1.11.0

---

lib/solid_queue.rb
lib/solid_queue/engine.rb

In addition, introduce load hooks for `:solid_queue`.
This solution is borrowed from the GoodJob codebase.

Fix setting Rails logger by default.

---

app/models/solid_queue/ready_execution.rb

This is another take on https://github.com/rails/solid_queue/pull/229, that tries to solve a deadlock like this:
```
*** (1) TRANSACTION:
TRANSACTION 5223, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
LOCK WAIT 5 lock struct(s), heap size 1128, 3 row lock(s), undo log entries 2
MySQL thread id 172, OS thread handle 281471652687808, query id 11099 192.168.0.5 root update
INSERT INTO `solid_queue_ready_executions` (`job_id`, `queue_name`, `priority`, `created_at`) VALUES (469, 'default', 0, '2024-05-21 01:15:11.201125')
*** (1) HOLDS THE LOCK(S):
RECORD LOCKS space id 12 page no 4 n bits 264 index PRIMARY of table `handson`.`solid_queue_ready_executions` trx id 5223 lock_mode X locks rec but not gap
Record lock, heap no 144 PHYSICAL RECORD: n_fields 7; compact format; info bits 0 …
```

Delete ready_executions by PK instead of job_id when claiming

---

app/models/solid_queue/claimed_execution.rb
lib/solid_queue/supervisor.rb
test/integration/processes_lifecycle_test.rb
test/unit/supervisor_test.rb

Orphaned executions shouldn't happen as part of regular operation, but some people have reported them (#159). The only way I can think of this happening could be that a worker gets deregistered while still working normally so that it happens to be claiming executions while the process record is deleted. This means that the callback to release claimed executions might not yet see the executions that are being claimed at the same time, and as such, it won't release any. Or, in other words, those executions would get claimed by a process that's getting deleted and that once they're committed to the DB, it no longer exists.
To recover from this scenario, as well as checking for processes with an expired heartbeat, the supervisor will also check for orphaned executions and release them.

Release any orphaned claimed executions as part of the process prune

---

README.md

Just a few small tweaks... feel free to ask me to explain these changes if the reasons are not clear.  I'm happy to go into as much or as little depth as you'd like, either in comments on the PR or in a Zoom call or whatever else works best for you.

quick grammar fixup in README.md

---

README.md
app/models/solid_queue/job.rb
app/models/solid_queue/recurring_execution.rb
lib/solid_queue/dispatcher.rb
lib/solid_queue/dispatcher/recurring_schedule.rb
lib/solid_queue/dispatcher/recurring_task.rb
lib/solid_queue/log_subscriber.rb
test/integration/instrumentation_test.rb
test/models/solid_queue/job_test.rb
test/unit/log_subscriber_test.rb
test/unit/recurring_task_test.rb

Some changes related to errors when enqueuing jobs: 
- ~Raise `ActiveJob::EnqueueError` on `ActiveRecordError` on enqueuing, as Active Job expects and handles.~ Raise `SolidQueue::Job::EnqueueError` on  `ActiveRecordError` on enqueuing. The reason is that we can't easily control what happens when something goes wrong on enqueuing if the jobs are enqueued by Rails or other gems (eg. `Turbo::Streams::BroadcastJob`, `ActiveStorage::AnalyzeJob`...), because the only way is to check what the return value of the call to `perform_later` is, or to pass a block to that method to fetch the error that gets set in `enqueue_error`. In this way at least the error will bubble up and you can rescue or let it be raised.
- Fix bug when enqueuing the job for a recurring task fails (reported in #251):  as …

Improve error handling on enqueuing

---

app/models/solid_queue/failed_execution.rb
test/dummy/app/jobs/infinite_recursion_job.rb
test/models/solid_queue/failed_execution_test.rb

Otherwise it can get really big for `SystemStackError` errors, and not fit in the DB text column.
Assuming an average of 150 characters per backtrace line, limting to 400 would be around 60K characters plus the error name and error message, that are usually small, and the JSON attributes and other JSON serialization characters.
This is the first approach to this. I'll change this to more sophisticated truncation that checks the column size and calculates how much it needs to truncate instead of using a fixed number.

Truncate error backtrace when saving failed executions

---

lib/puma/plugin/solid_queue.rb
test/integration/puma/plugin_test.rb

Puma fires up the background hooks before the ```on_booted``` event. Since the plugin registers the ```monitor_solid_queue``` after Puma is fully booted, it doesn't get executed.
The fix is to move the ```monitor_solid_queue``` out of the ```on_booted``` and check whether the SolidQueue has started in the ```solid_queue_dead?```.
Fixes #222 
/cc @K0H205

Fix Supervisor monitoring in Puma's plugin

---

app/models/solid_queue/failed_execution.rb

So that instead of truncating to a fixed amount of lines, we check how much space we have and add lines until we hit the limit.
This is a follow-up to #260

Improve backtrace truncation

---

lib/solid_queue/log_subscriber.rb
test/unit/log_subscriber_test.rb

It was being set to the whole payload 😅 🤦‍♀️  Also, use `iso8601` format for dates in log events.

Fix `pruned` attribute on `deregister_process` event

---

Gemfile.lock
app/models/solid_queue/semaphore.rb
test/integration/concurrency_controls_test.rb

Per all of my earlier discussion, Postgres transactions become invalid upon any database contraint invalidating an operation and make all follow on database interactions invalid until a rollback is executed.
Semephore#attempt_creation uses a rather common database pattern to rely on database locks to reliably syncrhronize based on uniqueness of values.  The catch is that Postgresql requires a little more handholding to use this pattern.  By wrapping just the Semaphore.create statement in a SAVEPOINT (a pretend nested transaction), we have what appears to be a transparent operation that works across all of the other supported databases without any known consequences AND allows Postgres to continue to work as expected per the existing code.
This change works across the Solid supported …

Fixes #224.  I believe this is a Postgres only issue

---

UPGRADING.md
app/models/solid_queue/recurring_execution.rb
app/models/solid_queue/recurring_task.rb
app/models/solid_queue/recurring_task/arguments.rb
app/models/solid_queue/semaphore.rb
db/migrate/20240719134516_create_recurring_tasks.rb
lib/solid_queue/configuration.rb
lib/solid_queue/dispatcher.rb
lib/solid_queue/dispatcher/recurring_schedule.rb
test/dummy/db/schema.rb
test/integration/concurrency_controls_test.rb
test/integration/forked_processes_lifecycle_test.rb
test/integration/instrumentation_test.rb
test/integration/puma/plugin_testing.rb
test/integration/recurring_tasks_test.rb
test/models/solid_queue/job_test.rb
test/models/solid_queue/recurring_task_test.rb
test/test_helper.rb
test/unit/dispatcher_test.rb
test/unit/fork_supervisor_test.rb
test/unit/hooks_test.rb
test/unit/worker_test.rb

This is a pre-requisite to add support for dynamic recurring tasks in the future and to allow for the execution of a task on-demand, for example, from Mission Control.

Store canonical recurring tasks in the DB

---

db/migrate/20240819165045_change_solid_queue_recurring_tasks_static_to_not_null.rb
test/dummy/db/schema.rb

This ensures the recurring tasks static is always either `TRUE` or `FALSE` (never `NULL`).

Avoid three-state boolean (TRUE / FALSE / NULL) for `solid_queue_recurring_tasks` `static`

---

UPGRADING.md
app/models/solid_queue/claimed_execution.rb
app/models/solid_queue/process.rb
app/models/solid_queue/process/executor.rb
app/models/solid_queue/process/prunable.rb
db/migrate/20240811173327_add_name_to_processes.rb
db/migrate/20240813160053_make_name_not_null.rb
lib/solid_queue/configuration.rb
lib/solid_queue/log_subscriber.rb
lib/solid_queue/processes/base.rb
lib/solid_queue/processes/poller.rb
lib/solid_queue/processes/registrable.rb
lib/solid_queue/processes/runnable.rb
lib/solid_queue/supervisor.rb
lib/solid_queue/supervisor/async_supervisor.rb
lib/solid_queue/supervisor/fork_supervisor.rb
lib/solid_queue/supervisor/maintenance.rb
test/dummy/db/schema.rb
test/integration/forked_processes_lifecycle_test.rb
test/integration/instrumentation_test.rb
test/models/solid_queue/claimed_execution_test.rb
test/models/solid_queue/process_test.rb
test/unit/async_supervisor_test.rb
test/unit/configuration_test.rb
test/unit/dispatcher_test.rb
test/unit/fork_supervisor_test.rb
test/unit/log_subscriber_test.rb
test/unit/worker_test.rb

This applies to:
- Killed workers that the supervisor detects as dead.
- Reaped workers without a clear exit status.
- Orphaned executions that somehow lost their worker.
- Workers whose heartbeat expired.
To do this easily, since the supervisor doesn't register all workers for efficiency, we need to rely on a new unique identifier that links the supervisor with their configured processes. Since the registration happens after forking, the supervisor doesn't know the registered process IDs of its supervised processes. This unique identifier is a `name` that gets randomly generated when the process is instantiated. This made me realise I was reusing the configured processes object to start new processes, which is quite prone to issues with already created thread pools and stuff like that 😬 …

Fail in-progress jobs when the worker running them exits abnormally

---

app/models/solid_queue/recurring_execution.rb
app/models/solid_queue/recurring_task.rb

These need to be enqueued within the transaction that creates the recurring execution to avoid duplicate runs. However, if the job is set to `enqueue_after_transaction_commit = :always` or `:default` when we change the default, it won't work because we'll try to create the recurring execution without having actually enqueued the job. With this change, we bypass Active Job's enqueuing and enqueue directly with Solid Queue, running `enqueue` callbacks.

Support recurring jobs that defer enqueuing to after commit always

---

db/migrate/20240813160053_make_name_not_null.rb

This is a migration fix added by https://github.com/rails/solid_queue/commit/76d2c0f62e60663407bf0bba384e8d667f9cc3e3.
Since `up` is a change to NOT NULL, `down` must undo it.

Fixed broken rollback migratio in processes' name

---

lib/solid_queue/configuration.rb
lib/solid_queue/supervisor.rb
test/unit/configuration_test.rb
test/unit/fork_supervisor_test.rb

Two improvements: 
- Use default configuration when the one given is empty, W¡which happens for example when you have solid queue configuration for an environment but not for others, so you can't find the `workers` and `dispatchers` keys.
- Don't try to start a supervisor on an empty configuration. It leads to weird errors, especially when forking, such as
`Errno::ECHILD` when trying to check on the children status without having forked any children.
I want to improve this with a generic configuration validation step, that would check this and other things, and abort/raise if there are any problems, but this will do for now.
Closes #298

Improve handling of empty configuration

---

app/models/solid_queue/claimed_execution.rb
app/models/solid_queue/process.rb
app/models/solid_queue/process/executor.rb
lib/solid_queue/supervisor/maintenance.rb
test/integration/forked_processes_lifecycle_test.rb
test/models/solid_queue/process_test.rb

This is a follow-up to #277.
In that case, we weren't correctly failing executions as a consequence of the prune because the processes would get deleted via a callback without going through the regular prune. Leave this to the prune itself instead of relying on the callbacks and only deregister supervised processes when not pruning. This also saves a query because we check whether we have a supervisor or not before trying to find supervisees.

Fix issue when pruning a supervisor and its supervisees via callbacks

---

lib/solid_queue/processes/poller.rb
test/integration/instrumentation_test.rb

Should close https://github.com/rails/solid_queue/issues/311. I wasn't sure how interesting the tests should be, but I did my best to show _something_ happening.

Wrap polling within instrumentation

---

app/models/solid_queue/process/prunable.rb
lib/solid_queue/processes/process_exit_error.rb
lib/solid_queue/processes/process_missing_error.rb
lib/solid_queue/processes/process_pruned_error.rb
lib/solid_queue/supervisor/fork_supervisor.rb
lib/solid_queue/supervisor/maintenance.rb

Move error classes to their own files so they can be loaded by Zeitwerk

---

.github/workflows/main.yml

Simply updates workflow to latest Ruby, as a new (every other month) release dropped yesterday, Sept 3rd.
- https://www.ruby-lang.org/en/news/2024/09/03/3-3-5-released/
- https://github.com/ruby/ruby/releases/tag/v3_3_5
Quick follow up to the the following which was ~1 day early it seems. 😅 
- https://github.com/rails/solid_queue/pull/319

Bump workflow to latest Ruby from 3.3.4 to 3.3.5

---

README.md

https://github.com/rails/solid_queue/issues/328
When running a small / hobby project (maybe to test solid queue) it's good to be able to test it with one Database. I propose to add instructions to the README.
If this PR gets accepted, happy to create a very similar one for Solid Cache

Add instructions to run with a single database

---

app/models/solid_queue/process/prunable.rb
lib/solid_queue/processes/base.rb
lib/solid_queue/processes/registrable.rb
lib/solid_queue/processes/runnable.rb
lib/solid_queue/supervisor.rb
lib/solid_queue/supervisor/maintenance.rb
test/unit/supervisor_test.rb
test/unit/worker_test.rb

This is a simple way to mitigate the effects of a computer going to sleep and then coming back to life, with processes with expired heartbeats that are, however, alive. It came up as part of the quest to reproduce another unrelated error in #324. It's not trivial for the supervisor to know whether a process is actually alive or not because the pid might have been reassigned by the OS to a different process. It can't rely on its registered supervisees either because we might be running multiple supervisors. We could possibly check its current forks, whether the `pid` matches, and in that case, skip the pruning, but I'm wary about introducing complicated logic there because the risk is ending up with dead registered processes and locked jobs. 
Since this scenario should happen only in …

Handle scenarios where registered processes disappear outside regular flow

---

README.md
UPGRADING.md
lib/active_job/queue_adapters/solid_queue_adapter.rb
lib/solid_queue.rb

See the discussion at https://github.com/rails/rails/pull/52659. Adapters should set their own behaviour without making users choose. If users want to choose, they can just use Active Job's configuration. Besides, we're changing the value of this to `true` to make it harder for people to run into trouble in the future when switching adapters.

Set `enqueue_after_transaction_commit` to `true` and don't allow changing it

---

app/models/solid_queue/process.rb
lib/solid_queue/processes/registrable.rb
test/models/solid_queue/process_test.rb

For example, in case of a previous heartbeat failed because of a DB issue (with SQLite depending on configuration, a `BusyException` is not rare) and we still have the unpersisted value in `last_heartbeat_at`, which means that `with_lock` will result in:
```
RuntimeError: Locking a record with unpersisted changes is not supported
```
Fixes #350

Clear previous changes before locking process for heartbeat

---

lib/solid_queue/cli.rb

With the introduction of `bin/jobs` in #308, I noticed that it ignores the `SOLID_QUEUE_CONFIG` environment variable (and the recently introduced `SOLID_QUEUE_RECURRING_SCHEDULE`), while `rails solid_queue:start` still respects both of them.
This PR is my attempt to fix it.
Please let me know if it is worth adding tests for the `SolidQueue::Cli`.
Also, I hope that the direction is correct, although the logic duplicates `default_options` from `SolidQueue::Configuration`.

Update Thor CLI options to respect ENV variables for default values

---

lib/solid_queue/configuration.rb

First, thanks for all of your work on this gem! I love watching the progress.
I was reviewing the recurrence implementation and noticed the memoized instance variable name was shared for both `#recurring_tasks` and `#recurring_tasks_config`. This appears to have been introduced in 0aa1644e38dd8c8cfcaf6d0ce3cd9e22ebd1a90b.
This isn't causing any bugs for me currently, but I figured this PR would help prevent any potential issues in the future.

Fix memoization for `#recurring_tasks_config`

---

app/models/solid_queue/record.rb
lib/solid_queue/supervisor/pidfile.rb

This commit addresses the following warnings appeared at Rails Nightly CI https://buildkite.com/rails/rails-nightly/builds/1095#019249e3-405c-4c52-ad8d-497f46a5c6a5/1244-1249
```ruby
/usr/local/lib/ruby/gems/3.4.0+0/gems/solid_queue-1.0.0/lib/solid_queue/supervisor/pidfile.rb:32: warning: assigned but unused variable - e
/usr/local/lib/ruby/gems/3.4.0+0/gems/solid_queue-1.0.0/app/models/solid_queue/record.rb:7: warning: ambiguous `**` has been interpreted as an argument prefix
```

Address Ruby warnings

---

lib/solid_queue/processes/runnable.rb

This commit removes one of the redundant `run` methods in `SolidQueue::Processes`
Here are the warning messages appeared at Rails Nightly CI: https://buildkite.com/rails/rails-nightly/builds/1091#019244bc-9d36-476d-8924-5e2bea4cb728/1173-1176
```
/usr/local/lib/ruby/gems/3.4.0+0/gems/solid_queue-1.0.0/lib/solid_queue/processes/runnable.rb:52: warning: method redefined; discarding old run
/usr/local/lib/ruby/gems/3.4.0+0/gems/solid_queue-1.0.0/lib/solid_queue/processes/runnable.rb:44: warning: previous definition of run was here
```

Remove redundant `run` methods in `SolidQueue::Processes`

---

app/models/solid_queue/recurring_task.rb

So we can redirect to it after enqueuing manually from Mission Control.

Return enqueued active job from `RecurringTask#enqueue`

---

.github/workflows/main.yml
.gitignore
.rubocop.yml
README.md
app/models/solid_queue/queue_selector.rb
bin/setup
test/dummy/bin/jobs
test/dummy/config/application.rb
test/dummy/config/database.yml
test/dummy/config/environments/development.rb
test/dummy/config/environments/production.rb
test/dummy/config/environments/test.rb
test/dummy/db/queue_schema.rb
test/models/solid_queue/job_test.rb
test/models/solid_queue/ready_execution_test.rb

We were altering the original order to be exact names and then prefixes in the order returned by the DB, which doesn't need to be the order specified for the worker. This change ensures the order is respected. Besides this, this also documents a bit the performance implications of the different ways to specify queues per worker. 
This fixes #360.

Fix queue order when combining multiple prefixes or prefixes and names 

---

app/models/solid_queue/queue.rb
test/unit/queue_test.rb

Hey all!
I'm using Yabeda to collect some metrics on a rails app that uses solid_queue. I send some metrics like the latency on each queue. Currently I use a little patch to accomplish that. I wonder if we can upstream this path just to make it more convenient for other people to access solid_queue's API. 🤔 
My Yabeda config example
```rb
Yabeda.configure do
group :solid_queue do
gauge :queue_latency, unit: :seconds, tags: [:queue]
end
collect do
SolidQueue::Queue.all.each do |queue|
solid_queue.queue_latency.set({ queue: queue.name }, queue.latency)
end
end
end
```

Add helper method to query the latency on the Queue object

---

lib/generators/solid_queue/install/install_generator.rb

Or, in other words, make the install generator idempotent.
Inspired by #349

Don't add `solid_queue.connects_to` configuration more than once

---

.gitignore
.rubocop.yml
Gemfile.lock
lib/solid_queue/processes/interruptible.rb
solid_queue.gemspec
test/dummy/config/initializers/enable_yjit.rb
test/integration/concurrency_controls_test.rb
test/integration/instrumentation_test.rb
test/integration/jobs_lifecycle_test.rb
test/integration/processes_lifecycle_test.rb
test/models/solid_queue/failed_execution_test.rb
test/test_helper.rb
test/unit/worker_test.rb

Details for each of the commits are in the separate commit messages
- Some minor housekeeping with .gitignore, .rubocop.ymlt and solid_queue.gemspec
- Proposed update to the tests to silence successful tests from outputting backtraces (keep the test output clean where possible and only output for the unexpected 
- Proposed reimplementation of the Interruptible concern to help mitigate some mysql database connectivity issues.

Reimplement Interruptible

---

lib/solid_queue/app_executor.rb

Currently, the default value `application.active_support` is applied for source. This does not identify it as an exception raised inside SolidQueue.
> source: a String about the source of the error. The default source is "application". Errors reported by internal libraries may set other sources; the Redis cache library may use "redis_cache_store.active_support", for instance. Your subscriber can use the source to ignore errors you aren't interested in.
This is a quote from the [rails guide](https://github.com/rails/rails/blob/v8.0.0/guides/source/error_reporting.md?plain=1#L216-L220).
Follow this guide to specify the source so that it can be determined that the error originated from inside SolidQueue.
Fixes #446

Specify `source` of SolidQueue to ErrorReporter

---

lib/solid_queue/log_subscriber.rb

As this would usually mean that some process got reparented to the process with PID 1, and that's why the supervisor doesn't know about it.
Addresses #442

Skip warning when replacing missing fork if supervisor has PID 1

---

lib/solid_queue/configuration.rb
lib/solid_queue/supervisor.rb
test/dummy/config/recurring_with_invalid.yml
test/test_helper.rb
test/test_helpers/configuration_test_helper.rb
test/test_helpers/processes_test_helper.rb
test/unit/configuration_test.rb
test/unit/supervisor_test.rb

I took a first crack at resolving #414. I think it's a little bit of a blunt solution.
Resolves #414

Error When an Invalid Recurring Task is Configured

---

lib/solid_queue/configuration.rb
lib/solid_queue/supervisor.rb
test/dummy/config/recurring_with_invalid.yml
test/unit/configuration_test.rb
test/unit/supervisor_test.rb

Small follow-up to #427 to also fail when the DB connection pool is too small.

Validate DB connection pool before starting supervisor

---

lib/solid_queue/dispatcher.rb
lib/solid_queue/processes/interruptible.rb
lib/solid_queue/processes/poller.rb
lib/solid_queue/worker.rb
test/unit/dispatcher_test.rb
test/unit/worker_test.rb

The Worker and Dispatcher share the same poll loop logic (Poller#start_loop) while having different functional requirements. The Worker is polling despite not being able to execute new jobs if at capacity. The Dispatcher does require polling, but is reliant on shared logic in Poller#start_loop for a Dispatcher specific optimization.
This PR allows the Worker to switch from polling to wake-on-event when its at capacity and eliminates the overhead of Worker#poll (really Worker#claim_executions) when it's known ahead of time #poll will be a no-op.
Changes:
Move the logic controlling the sleep interval from Poller#start_loop into Worker#poll and Dispatcher#poll by requiring #poll to return the `delay` value passed into interruptible_sleep.
Poller#start_loop:
- Removes the test based on the …

Specialize Dispatcher and Worker looping

---

README.md
app/models/solid_queue/job/clearable.rb

Useful for row-based replication setups where fast, big deletions can cause problems.

Add an option to sleep between deleted batches when clearing jobs

---

app/models/solid_queue/recurring_task.rb

To aid with monitoring for delayed recurring tasks.

Add `last_enqueued_time` and `previous_time` to `RecurringTask`

---

README.md

Fixed small writing error, words "need to" were used twice.

Fixed README.md sentence

---

lib/solid_queue/configuration.rb
test/dummy/config/recurring_with_production_only.yml
test/unit/configuration_test.rb

For example, `production` only, and the configuration is being loaded for `development`. In this case, we can't take the env key as the task definition, failing to load Solid Queue at all.
Fixes https://github.com/rails/solid_queue/issues/468

Don't fail when recurring tasks are defined for another environment

---

solid_queue.gemspec

This message is sort of long, and it seems unlikely that people who are upgrading are not upgrading all the way to latest?
I'd probably just remove this entirely (in favour of release notes, changelogs, upgraders reviewing upstream first, etc) but short of that, maybe reduce length...?

Simplify upgrade instructions in `post_install_message`

---

lib/solid_queue/configuration.rb
test/unit/configuration_test.rb

For example, when there's an entry for an environment other than the current one being used and that one is empty.

Fix case where a recurring task key is empty in the config

---

README.md

In doing a fresh setup with Rails 8, I followed the instructions but missed the fact that in the fresh install Rails doesn't include a `primary` key for the `development` database. 
This is likely because `solid_queue` isn't necessary in development. In the instructions to setup the multi-db in development, however, I missed the small addition due to the lack of `diff` addition. 
This PR makes it a bit more clear for folks that you need the `primary` key in addition to the `queue` key. Otherwise, it seems like Rails just ignores the `queue` key.

chore: Updates README to include small addition of plus for development multi db

---

solid_queue.gemspec

When attempting to install SQ 1.1.2 on a Ubuntu 22.04LTS system with default ruby (3.0.5) and Rails 7.1 it fails with the following error:
```
SyntaxError: /usr/lib/ruby/gems/3.0.0/gems/solid_queue-1.1.2/lib/solid_queue/processes/interruptible.rb:25: syntax error, unexpected ')'
queue.pop(timeout:).tap { queue.clear }
```
Using Ruby 3.1 there's no such error. It therefore seems that the gemspec should specify Ruby 3.1 as the minimum ruby version and not just Rails 7.1.

Require Ruby v3.1+

---

.github/workflows/main.yml
Gemfile.lock.ruby_3_1_6
README.md
app/models/solid_queue/scheduled_execution.rb
lib/solid_queue/dispatcher.rb
lib/solid_queue/engine.rb
lib/solid_queue/processes/base.rb
lib/solid_queue/processes/interruptible.rb
lib/solid_queue/processes/og_interruptible.rb
solid_queue.gemspec
test/models/solid_queue/claimed_execution_test.rb
test/unit/dispatcher_test.rb
test/unit/worker_test.rb

- Addresses Ruby version issues.
- Ruby 3.1.6 Thread::Queue.pop does not support a timeout option.  To address this issue, given that Ruby 3.1.6 is 2 months from EOL, this PR conditionally includes either the current version of Interruptible or the original implementation of Interruptible.  It's intended this part of the PR should be removed once SQ raising the min supported Ruby to >= 3.2
- Fixes claimed_execution_test to support Ruby 3.4+ (different backtrace formatting)
- Updates the Github actions to test a major subset of the rubies between 3.1.6 - 3.4.1.
- Required special case handling for Ruby 3.1.6 because of a dependency issue with Zeitwerk.
- Added error reporting in Interruptible#interruptible_sleep.  In theory, this shouldn't ever be needed, but since I thought that with the …

Fix issue 482

---

lib/solid_queue.rb
lib/solid_queue/dispatcher.rb
lib/solid_queue/lifecycle_hooks.rb
lib/solid_queue/scheduler.rb
lib/solid_queue/supervisor.rb
lib/solid_queue/worker.rb
test/integration/lifecycle_hooks_test.rb

Expose new `on_exit` hook to allow post-shutdown cleanup actions.
Notes:
- I made it for all kind of processes, but I believe it would only be useful for workers as they are the only one that may require such hooks. Do you believe it should only be for workers now and add them for the others later?
- Dispatchers currently trigger `run_stop_hooks` in [after_shutdown](https://github.com/rails/solid_queue/blob/cb5d230ddbf6732f2b78a5d3748475bab3b1deb5/lib/solid_queue/dispatcher.rb#L11)  but workers trigger them at [before_shutdown](https://github.com/rails/solid_queue/blob/cb5d230ddbf6732f2b78a5d3748475bab3b1deb5/lib/solid_queue/worker.rb#L8), I changed it in this PR but was that the expected behavior?

feat: add on_exit hook

---

README.md

Small PR since I have noticed [this](https://github.com/rails/solid_queue/issues/67) issue already, following by by the [fix](https://github.com/rails/solid_queue/commit/7838ad4bcb1efeac7179065d780410df31879b74), but I think this was unintentionally omitted.

Fix README queues config value to array

---

app/models/solid_queue/claimed_execution.rb
test/dummy/app/jobs/provider_job_id_job.rb
test/models/solid_queue/claimed_execution_test.rb

Sometimes it's handy to have `provider_job_id` available within `perform`. The Sidekiq adapter does it and Rails allows for it:
https://github.com/rails/rails/blob/aa2bfad1a137c9add1b35de118b391494e13ca06/activejob/lib/active_job/core.rb#L35
So far I'm not sure how to test this and the suite doesn't appear to go so far as testing the execution of jobs or at least what is available within `perform()`. Some guidance would be much appreciated :)
Closes #514

Pass job.id to the executing job as provider_job_id for access within perform()

---

README.md
lib/solid_queue.rb
lib/solid_queue/dispatcher.rb
lib/solid_queue/lifecycle_hooks.rb
lib/solid_queue/scheduler.rb
lib/solid_queue/worker.rb
test/integration/lifecycle_hooks_test.rb

Makes it so that Workers will yield self to life cycle hooks and makes some adjustments related to what's public/private in them.
I did not do this for the dispatcher or supervisor as I felt that did not make sense.
closes #513

Have all processes yield self to lifecycle hooks

---

app/models/solid_queue/blocked_execution.rb

Microsoft SQL Server requires a deterministic order when using `limit` (aka you have to provide `ORDER BY`). By default, in the MSSQL adapter, we inject a `ORDER BY [primary_key]` clause to achieve so, if not any `order` has been specified in the query.
This now leads to an issue in Solid Queue, where `concurrency_key` is selected and MSSQL complains that `id` is not in its `SELECT` clause.
I first looked into fixing this in the SQL adapter, but then found a test in `activerecord` itself (`test_pluck_and_distinct`) that orders first before calling `distinct`. So I would suggest to align Solid Queue here and order by `concurrency_key` prior to calling `distinct`.
I am aware that the existing code works with SQlite, MySQL and PostgreSQL as these do not require to pass an `ORDER BY` clause …

Order by `concurrency_key` before distinct

---

app/models/solid_queue/claimed_execution.rb
test/unit/supervisor_test.rb

When workers 'die' because of various reasons, the supervisor unlocks the jobs that were being handled by those workers by deleting the `claimed_executions` for the job and creating `failed_executions`. However, it does not release any concurrency locks taken by the jobs. This can be an issue if the concurrency limit was reached for the job because no further jobs can run until the concurrency duration is reached.
In this PR, I call `job.unblock_next_blocked_job` when the supervisor releases all claimed executions of the worker.
Fixes https://github.com/rails/solid_queue/issues/546

Release concurrency locks when supervisor fails the jobs handled by workers

---

lib/solid_queue/processes/registrable.rb

Moving stop_heartbeat after shutdown so that workers are not considered dead during a graceful shutdown.
Details in https://github.com/rails/solid_queue/issues/568

fix(568): moving stop_heartbeat after shutdown 

---

lib/solid_queue/processes/interruptible.rb

This is to fix #570. 
It looks like this only effects windows. My testing shows the first read works, and the second read throws EWOULDBLOCK. This should pop back up to the poller loop and does another interruptible_sleep, which recreates
This probably isn't great, but it's better than the alternative, which is solid_queue doesn't work on windows at all.

rescue from EWOULDBLOCKWaitReadable

---

app/models/solid_queue/job.rb
app/models/solid_queue/recurring_task.rb
test/models/solid_queue/recurring_task_test.rb

*(Even though this will be overwritten by Active Job when called through `perform_later`.)
This is necessary for recurring tasks, where we run the `enqueue` callbacks manually and call `Job.enqueue`. We rely on `successfully_enqueued?` to know whether we need to record the recurring execution. We were setting that no matter what after calling `Job.enqueue` because we were relying on that to raise (which would be the case for Active Record errors).
In the case of discarding it because of concurrency controls, the job is simply not persisted but no error is raised, which means we were trying to record a recurring execution without a persisted job, which would raise.
Fixes #598

Set `successfully_enqueued` in `Job.enqueue`

---

test/dummy/app/jobs/infinite_recursion_job.rb
test/models/solid_queue/failed_execution_test.rb

I believe we should supress the `ERROR -- stack level too deep: nil` that's currently happening in the test suite:
The failure is intentional (we're exercising a `SystemStackError` on purpose), but the noisy log isn’t documented and has already confused contributors into thinking it's a real test failure (see #527).

Supress expected warning for test suite

---

lib/solid_queue/cli.rb

Hello! Thank you for all your work on Solid Queue!
Recently, in v1.2.0, you introduced a support for `SOLID_QUEUE_SKIP_RECURRING` as an alternative to `--skip-recurring`. This is really helpful for us with our Heroku setup, so many thanks!
However, when we upgraded to v1.2.0, we noticed that it doesn't actually skip the recurring jobs. I dug into the code and I think the problem is that without the `--skip-recurring` flag, the `options` that are passed to `SolidQueue::Supervisor.start` already contain `skip_recurring: false`. The default options from `Configuration` don't override this.
To me, the best solution seems to be to remove the `default: false`, since the actual defaults are applied by `Configuration` anyway.
I hope you agree and that this can be included soon! Until then, we're …

Fix `SOLID_QUEUE_SKIP_RECURRING` env variable not doing anything

---

solid_queue.gemspec

This PR removes `Rakefile` from the list of files included in the gem package. I think that `Rakefile` is only needed for development and testing purposes and does not need to be distributed with the gem.

Remove Rakefile from gemspec files list

---

test/dummy/config/initializers/sqlite3.rb

When sqlite3 > 2.1.0 and rails < 8.0.0 we have the following warning when using Solid Queue:
```
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/sqlite3-2.5.0-x86_64-linux-gnu/lib/sqlite3/fork_safety.rb:43: warning: Writable sqlite database connection(s) were inherited from a forked process. This is unsafe and the connectio
ns are being closed to prevent possible data corruption. Please close writable sqlite database connections before forking.
```
This is polluting our CI logs and triggering warnings for people using Solid Queue with Rails 7.1 and 7.2 - although the behaviour is safe: https://github.com/rails/solid_queue/issues/324#issuecomment-2372245070
Also mentioned in: https://github.com/rails/solid_queue/issues/506

Supress sqlite fork warnings for rails 7.1 & 7.2

---

README.md

- Fixed grammar issues
- Standardized capitalization (e.g. "Dashboard UI setup")
- Improved clarity and removed redundant words in intro and config sections

Fix typos and improve formatting in README.md

---

.github/workflows/main.yml
docker-compose.yml
test/dummy/config/database.yml

Resolves: https://github.com/rails/solid_queue/issues/528
In order to avoid conflict with MySQL Protocol X, the port was changed to `33066`.
The change was tested locally by running `docker compose up`

fix: Change MySQL port to 33066

---

app/models/solid_queue/job.rb
test/models/solid_queue/job_test.rb

👋 
We've noticed inconsistent behavior between jobs enqueued normally and those enqueued in batches using `ActiveJob.perform_all_later`. When using batch enqueue, the job attribute `scheduled_at` is missing (unless `wait` or `wait_until` is used).
Besides being inconsistent, this causes a problem with Mission Control, as you can't view the details of a finished job due to this line: https://github.com/rails/mission_control-jobs/blob/7ac38357e33778099b8b76b5476bf36ad3b53bf2/lib/active_job/job_proxy.rb#L30, which throws the following exception:
```
can't convert NilClass into an exact number (TypeError)
minus_without_duration(other)
```
This PR makes the behavior consistent and adds tests.

Set `scheduled_at` in `enqueue_all`

---

Gemfile.lock
lib/puma/plugin/solid_queue.rb
solid_queue.gemspec

Puma 7 is no longer compatible with Solid Queue due to the change in hook names (https://github.com/rails/solid_queue/issues/633).
This PR is my attempt to fix it and support both new and old hook names.
Need advice on tests: should I just add Puma 7 to Appraisal, or should it be a matrix that tests all possible combinations of Puma and Rails versions?
Reference: https://github.com/puma/puma/releases/tag/v7.0.0

Add support for new Puma 7 hook names

---

app/models/solid_queue/claimed_execution.rb

close #641 
Prevents unnecessary events from being emitted when SolidQueue::ClaimedExecution is empty.

SolidQueue::ClaimedExecution.fail_all_with return early when the record is empty
